### ISSUE TITLE
推广下线页面问题

### ISSUE THREAD

**Issue by solebtc** [febobo/react-redux-start#26]
使用此账号登录，

515583695#qq.com
 查看推广页面，存在2个问题：
1. 科学计数问题，修改为正常的计数方式
   ![image](https://cloud.githubusercontent.com/assets/19500437/15812004/3e159c60-2be2-11e6-92fe-bf210d119561.png)

2.点击更换显示条数后，切换无效
![image](https://cloud.githubusercontent.com/assets/19500437/15812045/b8783134-2be2-11e6-8ef3-9a024c9c5fc1.png)

**Comment by on99** [comment]
https://github.com/febobo/react-redux-start/blob/238fe15b996b583f6b900d1ab22ea01198b95eb1/src/components/Offline/Offline.js#L18

`let offset = (page * limit) || 0`
